using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using ShapeSpecs.Core.Models;

namespace ShapeSpecs.UI.Forms
{
    /// <summary>
    /// Form for editing specifications, notes, and other shape metadata
    /// </summary>
    public partial class EditorForm : Form
    {
        /// <summary>
        /// Gets the edited text
        /// </summary>
        public string EditedText { get; private set; }

        /// <summary>
        /// Gets the edited name/title
        /// </summary>
        public string EditedName { get; private set; }

        /// <summary>
        /// Initializes a new instance of the EditorForm
        /// </summary>
        public EditorForm()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Initializes a new instance of the EditorForm with the specified text and name/title
        /// </summary>
        /// <param name="text">The initial text</param>
        /// <param name="name">The initial name/title</param>
        /// <param name="title">Title for the form</param>
        /// <param name="readOnly">Whether the text is read-only</param>
        public EditorForm(string text, string name, string title, bool readOnly = false)
            : this()
        {
            this.Text = title;
            txtName.Text = name;
            txtContent.Text = text;
            txtContent.ReadOnly = readOnly;
            txtName.ReadOnly = readOnly;

            if (readOnly)
            {
                btnOK.Text = "Close";
                btnCancel.Visible = false;
            }
        }

        /// <summary>
        /// Sets up the form for editing a note
        /// </summary>
        /// <param name="note">The note to edit, or null for a new note</param>
        /// <returns>The initialized form</returns>
        public static EditorForm ForNote(Note note = null)
        {
            var form = new EditorForm(
                note?.Text ?? string.Empty,
                note?.Category ?? string.Empty,
                note == null ? "Add Note" : "Edit Note");
            
            form.lblName.Text = "Category:";
            return form;
        }

        /// <summary>
        /// Sets up the form for editing a text specification
        /// </summary>
        /// <param name="name">The specification name</param>
        /// <param name="value">The specification value</param>
        /// <returns>The initialized form</returns>
        public static EditorForm ForSpecification(string name = "", string value = "")
        {
            var form = new EditorForm(
                value,
                name,
                string.IsNullOrEmpty(name) ? "Add Specification" : "Edit Specification");
            
            form.lblName.Text = "Name:";
            return form;
        }

        /// <summary>
        /// Sets up the form for viewing content
        /// </summary>
        /// <param name="content">The content to view</param>
        /// <param name="title">The title of the content</param>
        /// <param name="formTitle">The form title</param>
        /// <returns>The initialized form</returns>
        public static EditorForm ForViewing(string content, string title, string formTitle)
        {
            return new EditorForm(content, title, formTitle, true);
        }

        private void btnOK_Click(object sender, EventArgs e)
        {
            // Save the edited text and name
            EditedText = txtContent.Text;
            EditedName = txtName.Text;
            
            this.DialogResult = DialogResult.OK;
            this.Close();
        }

        private void btnCancel_Click(object sender, EventArgs e)
        {
            this.DialogResult = DialogResult.Cancel;
            this.Close();
        }

        #region Designer Generated Code

        // TODO: Add the InitializeComponent method and fields
        // This would normally be generated by the Windows Forms Designer
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtContent;
        private System.Windows.Forms.Button btnOK;
        private System.Windows.Forms.Button btnCancel;

        /// <summary>
        /// Initialize the UI components - simplified for this example
        /// In a real project, this would be generated by the Windows Forms Designer
        /// </summary>
        private void InitializeComponent()
        {
            this.lblName = new System.Windows.Forms.Label();
            this.txtName = new System.Windows.Forms.TextBox();
            this.txtContent = new System.Windows.Forms.TextBox();
            this.btnOK = new System.Windows.Forms.Button();
            this.btnCancel = new System.Windows.Forms.Button();
            
            // lblName
            this.lblName.AutoSize = true;
            this.lblName.Location = new System.Drawing.Point(12, 15);
            this.lblName.Name = "lblName";
            this.lblName.Size = new System.Drawing.Size(38, 13);
            this.lblName.TabIndex = 0;
            this.lblName.Text = "Name:";
            
            // txtName
            this.txtName.Location = new System.Drawing.Point(15, 31);
            this.txtName.Name = "txtName";
            this.txtName.Size = new System.Drawing.Size(457, 20);
            this.txtName.TabIndex = 1;
            
            // txtContent
            this.txtContent.Location = new System.Drawing.Point(15, 57);
            this.txtContent.Multiline = true;
            this.txtContent.Name = "txtContent";
            this.txtContent.ScrollBars = System.Windows.Forms.ScrollBars.Both;
            this.txtContent.Size = new System.Drawing.Size(457, 253);
            this.txtContent.TabIndex = 2;
            
            // btnOK
            this.btnOK.Location = new System.Drawing.Point(316, 326);
            this.btnOK.Name = "btnOK";
            this.btnOK.Size = new System.Drawing.Size(75, 23);
            this.btnOK.TabIndex = 3;
            this.btnOK.Text = "OK";
            this.btnOK.UseVisualStyleBackColor = true;
            this.btnOK.Click += new System.EventHandler(this.btnOK_Click);
            
            // btnCancel
            this.btnCancel.Location = new System.Drawing.Point(397, 326);
            this.btnCancel.Name = "btnCancel";
            this.btnCancel.Size = new System.Drawing.Size(75, 23);
            this.btnCancel.TabIndex = 4;
            this.btnCancel.Text = "Cancel";
            this.btnCancel.UseVisualStyleBackColor = true;
            this.btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            
            // EditorForm
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(484, 361);
            this.Controls.Add(this.btnCancel);
            this.Controls.Add(this.btnOK);
            this.Controls.Add(this.txtContent);
            this.Controls.Add(this.txtName);
            this.Controls.Add(this.lblName);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedDialog;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "EditorForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Editor";
        }

        #endregion
    }
}